[Lignes strictement identiques entre deux tableaux Excel](https://www.youtube.com/watch?v=LkMc0RDNmq8&list=PLpQBnWleLAauKmgcdndmEr81iIIoW9_Wi&index=18)

Date : 22/05/2025

In [13]:
import pandas as pd

In [14]:
tab1 = pd.read_excel('data/join2.xlsx', sheet_name='Feuil1')
tab1.head()

             Nom    Prénom
0        Bonbeur      Jean
1        Hèresse    Mégane
2           Noix  Stéphane
3         Gature    Emilie
4  De MontéCarlo   Coralie

In [15]:
tab2 = pd.read_excel('data/join2.xlsx', sheet_name='Feuil2')
tab2.head()

             Nom    Prénom
0        Bonbeur      Jean
1        Hèresse    Mégane
2           Noix  Stéphane
3         Gature    Emilie
4  De MontéCarlo   Coralie

In [16]:
# Indexation des deux DataFrames
tab1.set_index(['Nom', 'Prénom'], inplace=True)
tab2.set_index(['Nom', 'Prénom'], inplace=True)

In [17]:
# Index communs des deux DataFrames
index_communs=tab1.index.intersection(tab2.index)

In [18]:
# Récupération des lignes communes
tab1_commun=tab1.loc[index_communs]
tab2_commun=tab1.loc[index_communs]

In [19]:
# Affichage des lignes communes
resultat=tab1_commun.join(tab2_commun)
resultat.reset_index()

              Nom    Prénom
0         Bonbeur      Jean
1         Hèresse    Mégane
2            Noix  Stéphane
3          Gature    Emilie
4   De MontéCarlo   Coralie
5          Hénéré    Nadège
6            Solo     Yohan
7             Jet    Claire
8         Braltar     Giles
9          Douche      Raël
10       Sarbaque      Anne
11           Lile   Maurice
12          Doeuf      John
13         Niomme    Gérard